CREATE TYPE "public"."class_status" AS ENUM('research', 'corpus_ready', 'active', 'demoted');--> statement-breakpoint
CREATE TYPE "public"."dispute_resolution" AS ENUM('pending', 'accepted_fp', 'rejected');--> statement-breakpoint
CREATE TYPE "public"."finding_severity" AS ENUM('critical', 'high', 'medium', 'low');--> statement-breakpoint
CREATE TYPE "public"."finding_status" AS ENUM('open', 'fixed', 'disputed', 'suppressed');--> statement-breakpoint
CREATE TYPE "public"."finding_tier" AS ENUM('verified', 'research');--> statement-breakpoint
CREATE TYPE "public"."fleet_posture" AS ENUM('unscanned', 'passing', 'findings_open', 'critical');--> statement-breakpoint
CREATE TYPE "public"."gate_failure_mode" AS ENUM('fail_open', 'fail_closed');--> statement-breakpoint
CREATE TYPE "public"."gate_mode" AS ENUM('off', 'block_verified', 'block_threshold');--> statement-breakpoint
CREATE TYPE "public"."member_role" AS ENUM('admin', 'member', 'viewer');--> statement-breakpoint
CREATE TYPE "public"."plan_tier" AS ENUM('free', 'team', 'scale');--> statement-breakpoint
CREATE TYPE "public"."scan_exec_mode" AS ENUM('hosted', 'runner', 'cli');--> statement-breakpoint
CREATE TYPE "public"."scan_status" AS ENUM('queued', 'running', 'completed', 'failed', 'timed_out');--> statement-breakpoint
CREATE TYPE "public"."scan_trigger" AS ENUM('push', 'pr', 'manual', 'schedule', 'fleet_change');--> statement-breakpoint
CREATE TABLE "audit_events" (
	"seq" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_events_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"org_id" text,
	"at" timestamp with time zone DEFAULT now() NOT NULL,
	"actor" text NOT NULL,
	"action" text NOT NULL,
	"subject" text DEFAULT '{}' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "benchmark_runs" (
	"id" text PRIMARY KEY NOT NULL,
	"corpus_version" text NOT NULL,
	"tool" text NOT NULL,
	"results" text NOT NULL,
	"published_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "disputes" (
	"id" text PRIMARY KEY NOT NULL,
	"finding_id" text NOT NULL,
	"user_id" text NOT NULL,
	"reason" text,
	"resolution" "dispute_resolution" DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "evidence_exports" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"scan_id" text NOT NULL,
	"platform" text NOT NULL,
	"control_map_version" text NOT NULL,
	"items" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "findings" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"scan_id" text NOT NULL,
	"fingerprint" text NOT NULL,
	"tier" "finding_tier" NOT NULL,
	"class_id" text NOT NULL,
	"severity" "finding_severity" NOT NULL,
	"locations" text NOT NULL,
	"surfaces" text[] NOT NULL,
	"reproduction" text,
	"confidence" numeric(4, 3),
	"explanation" text NOT NULL,
	"status" "finding_status" DEFAULT 'open' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "fleet_servers" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"name" text NOT NULL,
	"endpoint_or_repo" text NOT NULL,
	"last_scan_id" text,
	"posture" "fleet_posture" DEFAULT 'unscanned' NOT NULL,
	"config_hash" text
);
--> statement-breakpoint
CREATE TABLE "memberships" (
	"org_id" text NOT NULL,
	"user_id" text NOT NULL,
	"role" "member_role" DEFAULT 'member' NOT NULL,
	CONSTRAINT "memberships_org_id_user_id_pk" PRIMARY KEY("org_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "organizations" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"plan_tier" "plan_tier" DEFAULT 'free' NOT NULL,
	"llm_analysis_enabled" boolean DEFAULT true NOT NULL,
	"agent_loop_enabled" boolean DEFAULT false NOT NULL,
	"sso_connection_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "organizations_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "questionnaire_drafts" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"source_format" text NOT NULL,
	"answers" text NOT NULL,
	"review_status" text DEFAULT 'draft' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "repositories" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"github_repo_id" bigint NOT NULL,
	"name" text NOT NULL,
	"frameworks_detected" text[] DEFAULT '{}' NOT NULL,
	"surfaces_present" text[] DEFAULT '{}' NOT NULL,
	"gate_mode" "gate_mode" DEFAULT 'off' NOT NULL,
	"gate_failure_mode" "gate_failure_mode" DEFAULT 'fail_open' NOT NULL,
	"agent_loop_enabled" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "repositories_github_repo_id_unique" UNIQUE("github_repo_id")
);
--> statement-breakpoint
CREATE TABLE "rules" (
	"id" text PRIMARY KEY NOT NULL,
	"class_id" text NOT NULL,
	"ruleset_version_introduced" text NOT NULL,
	"default_ruleset" boolean DEFAULT false NOT NULL,
	"measured_tp_rate" numeric,
	"measured_fp_rate" numeric,
	"measured_against_corpus" text
);
--> statement-breakpoint
CREATE TABLE "runner_tokens" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"token_hash" text NOT NULL,
	"min_ruleset_version" text NOT NULL,
	"revoked_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "scans" (
	"id" text PRIMARY KEY NOT NULL,
	"org_id" text NOT NULL,
	"repository_id" text,
	"fleet_server_id" text,
	"trigger" "scan_trigger" NOT NULL,
	"execution_mode" "scan_exec_mode" NOT NULL,
	"ruleset_version" text NOT NULL,
	"commit_sha" text,
	"pr_number" integer,
	"status" "scan_status" DEFAULT 'queued' NOT NULL,
	"stage_timings" text DEFAULT '{}' NOT NULL,
	"posture_snapshot" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "suggested_fixes" (
	"id" text PRIMARY KEY NOT NULL,
	"finding_id" text NOT NULL,
	"kind" text NOT NULL,
	"content" text NOT NULL,
	"delivered_via" text
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" text PRIMARY KEY NOT NULL,
	"github_user_id" bigint NOT NULL,
	"email" text NOT NULL,
	"display_name" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_github_user_id_unique" UNIQUE("github_user_id")
);
--> statement-breakpoint
CREATE TABLE "vulnerability_classes" (
	"id" text PRIMARY KEY NOT NULL,
	"tier_target" "finding_tier" NOT NULL,
	"definition" text NOT NULL,
	"taxonomy_refs" text DEFAULT '[]' NOT NULL,
	"status" "class_status" DEFAULT 'research' NOT NULL,
	"corpus_case_count" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "disputes" ADD CONSTRAINT "disputes_finding_id_findings_id_fk" FOREIGN KEY ("finding_id") REFERENCES "public"."findings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "disputes" ADD CONSTRAINT "disputes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "evidence_exports" ADD CONSTRAINT "evidence_exports_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "evidence_exports" ADD CONSTRAINT "evidence_exports_scan_id_scans_id_fk" FOREIGN KEY ("scan_id") REFERENCES "public"."scans"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "findings" ADD CONSTRAINT "findings_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "findings" ADD CONSTRAINT "findings_scan_id_scans_id_fk" FOREIGN KEY ("scan_id") REFERENCES "public"."scans"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fleet_servers" ADD CONSTRAINT "fleet_servers_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fleet_servers" ADD CONSTRAINT "fleet_servers_last_scan_id_scans_id_fk" FOREIGN KEY ("last_scan_id") REFERENCES "public"."scans"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "questionnaire_drafts" ADD CONSTRAINT "questionnaire_drafts_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "repositories" ADD CONSTRAINT "repositories_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rules" ADD CONSTRAINT "rules_class_id_vulnerability_classes_id_fk" FOREIGN KEY ("class_id") REFERENCES "public"."vulnerability_classes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "runner_tokens" ADD CONSTRAINT "runner_tokens_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scans" ADD CONSTRAINT "scans_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "scans" ADD CONSTRAINT "scans_repository_id_repositories_id_fk" FOREIGN KEY ("repository_id") REFERENCES "public"."repositories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "suggested_fixes" ADD CONSTRAINT "suggested_fixes_finding_id_findings_id_fk" FOREIGN KEY ("finding_id") REFERENCES "public"."findings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "findings_scan_idx" ON "findings" USING btree ("scan_id");--> statement-breakpoint
CREATE UNIQUE INDEX "findings_fingerprint_idx" ON "findings" USING btree ("scan_id","fingerprint");